[versions]
junitVersion = "6.0.1"
assertjVersion = "3.27.6"

[libraries]
asciidoctorBlockSwitch = { module = "io.spring.asciidoctor:spring-asciidoctor-extensions-block-switch", version = "0.6.3" }
junitBom = { module = "org.junit:junit-bom", version.ref = "junitVersion" }
junitJupiterApi = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitVersion" }
junitJupiterEngine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitVersion" }
junitJupiterParams = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junitVersion" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher", version = "6.0.1" }
assertjCore = { module = "org.assertj:assertj-core", version.ref = "assertjVersion" }
okHttp = { module = "com.squareup.okhttp3:okhttp", version = "5.3.2" }
springData = { module = "org.springframework.data:spring-data-commons", version = "4.0.0" }
jakartaPersistenceApi = { module = "jakarta.persistence:jakarta.persistence-api", version = "3.2.0" }
jspecify = { module = "org.jspecify:jspecify", version = "1.0.0" }

[plugins]
asciidoctor = { id = "org.asciidoctor.jvm.convert", version = "4.0.5" }
jreleaser = { id = "org.jreleaser", version = "1.21.0" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm", version = "2.2.21" }
sonar = { id = "org.sonarqube", version = "7.2.0.6526" }
spotless = { id = "com.diffplug.spotless", version = "8.1.0" }
